data:
  image: redis:2.6
  command: /bin/true
db:
  image: redis:2.6
  command: redis-server
  volumes_from:
    - data
base:
  command: /bin/true
  build: .
logplex:
  image: logplex_base
  command: ./bin/compose_logplex
  hostname: logplex
  domainname: docker.local
  environment:
    - INSTANCE_NAME=logplex.docker.local
    - LOCAL_IP=127.0.0.1
  env_file:
    - logplex.env
  volumes_from:
    - base
  ports:
    - "8001:8001"
    - "8601:8601"
    - "6001:6001"
  links:
    - db
compile:
  command: env REBAR=rebar3 make compile
  image: logplex_base
  volumes:
    - ./src:/usr/src/app/src
    - ./rebar.config:/usr/src/app/rebar.config
    - ./Makefile:/usr/src/app/Makefile
  volumes_from:
    - base
test:
  image: logplex_base
  command: make test
  hostname: logplex
  domainname: docker.local
  environment:
    - INSTANCE_NAME=logplex.docker.local
    - LOCAL_IP=127.0.0.1
  volumes:
    - ./src:/usr/src/app/src
    - ./test:/usr/src/app/test
    - ./logplex.spec:/usr/src/app/logplex.spec
    - ./rebar.config:/usr/src/app/rebar.config
    - ./Makefile:/usr/src/app/Makefile
  volumes_from:
    - base
  links:
    - db

