data:
  image: redis:2.6
  command: /bin/true
db:
  image: redis:2.6
  command: redis-server
  volumes_from:
    - data
base:
  command: /bin/true
  build: .
  volumes:
    - ./:/usr/src/app
    - /usr/src/app/_build
compile:
  command: env REBAR=rebar3 make compile
  image: logplex_base
  volumes_from:
    - base
clean:
  command: env REBAR=rebar3 make clean
  image: logplex_base
  volumes_from:
    - base
logplex:
  image: logplex_base
  command: ./_build/default/rel/logplex/bin/logplex foreground
  hostname: logplex
  domainname: docker.local
  environment:
    - INSTANCE_NAME=logplex.docker.local
    - LOCAL_IP=127.0.0.1
  env_file:
    - logplex.env
  volumes_from:
    - base
  ports:
    - "8001:8001"
    - "8601:8601"
    - "6001:6001"
  links:
    - db
test:
  image: logplex_base
  command: make test
  hostname: logplex
  domainname: docker.local
  extra_hosts:
    - "server:127.0.0.1"
    - "evilserver:127.0.0.1"
  environment:
    - INSTANCE_NAME=logplex.docker.local
    - LOCAL_IP=127.0.0.1
  volumes:
    - ./test:/usr/src/app/test
    - ./logs:/usr/src/app/logs
    - ./logplex.spec:/usr/src/app/logplex.spec
  volumes_from:
    - base
  links:
    - db

