data:
  image: redis:2.6
  command: /bin/true
db:
  image: redis:2.6
  command: redis-server
  volumes_from:
    - data
base:
  command: /bin/true
  build: .
logplex:
  image: logplex_base
  command: ./bin/compose_logplex
  env_file:
    - logplex.env
  volumes_from:
    - base
  ports:
    - "8001:8001"
    - "8601:8601"
    - "6001:6001"
  links:
    - db
compile:
  command: make quick
  image: logplex_base
  volumes:
    - ./src:/usr/src/app/src
  volumes_from:
    - base
test:
  image: logplex_base
  command: bin/compose_test_logplex
  volumes:
    - ./src:/usr/src/app/src
    - ./test:/usr/src/app/test
    - ./logplex.spec:/usr/src/app/logplex.spec
  volumes_from:
    - base
  links:
    - db

